export const GET_ALL_POST = "GET_ALL_POST";
export const GET_DETAIL_POST = "GET_DETAIL_POST";
export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";
